In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3),
)

deepnet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3),
)

In [3]:
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[ 0.0350, -0.5845],
        [-0.2342,  0.5880]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.0731, -0.3818], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.4917, -0.6416],
        [ 0.6409,  0.6462]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.4869, -0.3604], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.0564, -0.4108],
        [ 0.0069,  0.6331],
        [ 0.6634,  0.4686]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.2547, -0.2732, -0.0397], requires_grad=True))
 


In [4]:
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName, paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print(numNodesInWide)
print(numNodesInDeep)

7
7


In [5]:
nparams = 0
for p in widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameter.' %p.numel())
        nparams += p.numel()

print('\n\nTotal of %s parameters' %nparams)

This piece has 8 parameter.
This piece has 4 parameter.
This piece has 12 parameter.
This piece has 3 parameter.


Total of 27 parameters


In [7]:
nparams = 0
for p in deepnet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' %p.numel())
        nparams += p.numel()

print('\n\nTotal of %s parameters' %nparams)

This piece has 4 parameters
This piece has 2 parameters
This piece has 4 parameters
This piece has 2 parameters
This piece has 6 parameters
This piece has 3 parameters


Total of 21 parameters
