In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
prob = 0.5

dropout = nn.Dropout(p=prob)

x = torch.ones(10)

y = dropout(x)
print(x)
print(y)
print(y*(1-prob))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 0., 0., 2., 2., 0., 2., 2.])
tensor([1., 1., 1., 0., 0., 1., 1., 0., 1., 1.])
tensor(1.4000)


In [8]:
dropout.eval()
y = dropout(x)
print(x)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [9]:
dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([0., 0., 2., 2., 2., 2., 2., 2., 2., 0.])
tensor(1.4000)


In [10]:
y = F.dropout(x, training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [14]:
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

#dropout.train()
y = dropout(x)
print(y)

tensor([0., 0., 0., 2., 2., 0., 2., 0., 2., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [13]:
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

dropout.train()
y = dropout(x)
print(y)

tensor([0., 2., 0., 2., 0., 0., 2., 0., 2., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 2., 2., 2., 0., 2., 2., 0., 0., 2.])
